# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'CV',                 url: 'cv'}
- {name: 'Research Interests', url: 'research'}
- {name: 'Current Projects',   url: 'current'}
- {name: 'Teaching',           url: 'teaching'}
- {name: 'Archive',            url: 'archive'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'square-bluesky',    link:    'https://twitter.com/paululele'}
- {icon: 'envelope',                link:   'mailto:ahui@gmu.edu'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
